In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('GPG.csv')
df

,year,serial,numprec,hwtsupp,gq,region,statefip,metro,metarea,county,farm,month,pernum,wtsupp,relate,age,sex,race,marst,popstat,bpl,yrimmig,citizen,mbpl,fbpl,nativity,hispan,sch,educ99,schlcoll,empstat,labforce,occ,occ1990,ind1990,occ1950,ind,ind1950,classwkr,occly,occ50ly,indly,ind50ly,classwly,wkswork1,wkswork2,hrswork,uhrswork,union,incwage,incbus,incfarm,inclongj,oincwage,srcearn,ftype,quhrswor,qwkswork,qincbus,qincfarm,qinclong,qincwage,qsrcearn,o_numprec,o_hwtsupp,o_gq,o_region,o_statefip,o_metro,o_metarea,o_county,o_farm,o_month,o_pernum,o_wtsupp,o_relate,o_age,o_sex,o_race,o_marst,o_popstat,o_bpl,o_yrimmig,o_citizen,o_mbpl,o_fbpl,o_nativity,o_hispan,o_educ,o_educ99,o_schlcoll,o_empstat,o_labforce,o_occ,o_occ1990,o_ind1990,o_occ1950,o_ind,o_ind1950,o_classwkr,o_occly,o_occ50ly,o_indly,o_ind50ly,o_classwly,o_wkswork1,o_wkswork2,o_hrswork,o_uhrswork,o_union,o_incwage,o_incbus,o_incfarm,o_inclongj,o_oincwage,o_srcearn,o_ftype,o_quhrswor,o_qwkswork,o_qincbus,o_qincfarm,o_qincwage,origrace,white,black,hisp,othrace,educorig,ba,adv,groupquar,potexp,potexp2,selfemp,military,employed,annhrs,ft,niincwage,incwageman,tcoincwage,tcinclongj,tcincwage,hrwage,perconexp,expendbase10,inflate,realhrwage,uncenrealhrwage,lnrwg,hdwfcoh,notalloc,basesamp,wagesamp,occ_orig,adj_occ,occ_2010_orig,ind_orig,adj_ind,ind_2002_orig,ind_2007_orig,occ_81,ind_81,occ_2000female,unmatched_fem_81,occ_2000male,unmatched_male_81,ind_2000,occ2000_81,ind2000_81,occ_1990,ind_1990,occ_1999,ind_1999,unmatched_occ_90,occ2000_90,unmatched_ind_90,ind2000_90,indname2000_90,unmatched_occ_99,occ2000_99,unmatched_ind_99,ind2000_99,indname2000_99,un_lnrealwg,northeast,northcentral,south,west,female,adj_ind2,adj_occ2,adj_occ2name,Agriculture,miningconstruction,durables,nondurables,Transport,Utilities,Communications,retailtrade,wholesaletrade,finance,SocArtOther,hotelsrestaurants,Medical,Education,professional,publicadmin,sumadj_ind,manager,business,financialop,computer,architect,scientist,socialworker,postseceduc,legaleduc,artist,lawyerphysician,healthcare,healthsupport,protective,foodcare,building,sales,officeadmin,farmer,constructextractinstall,production,transport,sumadj_occ,LEHS
0,1990,9677,1,1052.650024,1,12,36,2.0,5607.0,NaN,1.0,3,1,1052.650024,101,58,1,3,6,1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,12.0,NaN,NaN,10,2,335,335,871.0,390,871,896,28,335,390,871,896.0,28,52,6,35.0,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1052.650024,1,12,36,2,5607,NaN,1.0,3,1,1052.650024,101,58,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,200,72,NaN,0.0,10,2,335,335,871,390,871,896,28,335,390,871,896,28,52,6,35,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0,100,0,0,1,0,72,0,0,0,40,1600,0,0,1,1820,1,14200.0,14200.0,0.0,14200.0,14200.0,7.802198,64.639999,101.653999,1.572618,12.269874,12.269874,2.507147,1,1,1,1,335,526.0,NaN,871,837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,871.0,NaN,NaN,NaN,526.0,NaN,837.0,Individual and family services,NaN,NaN,NaN,NaN,NaN,2.507147,1,0,0,0,0,62,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
1,2009,64923,4,971.200012,1,33,5,2.0,NaN,NaN,NaN,3,4,1288.880005,1260,28,1,1,6,1,9900.0,NaN,NaN,9900.0,9900.0,1.0,0.0,12.0,10.0,NaN,10,2,5120,337,762.0,310,8660,836,21,5120,310,8660,836.0,22,52,6,40.0,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0.0,0,0.0,4,971.200012,1,33,5,2,9999,0.0,NaN,3,4,1288.880005,1260,28,1,100,6,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,5120,337,762,310,8660,836,21,5120,310,8660,836,22,52,6,40,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,10,100,0,0,1,2080,1,17680.0,17680.0,0.0,17680.0,17680.0,8.500000,100.063004,101.653999,1.015900,8.635149,8.635149,2.155841,0,1,1,1,5120,512.0,NaN,8660,866,NaN,8660.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.155841,0,0,1,0,0,68,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
2,1990,8425,1,1622.280029,1,12,36,3.0,5607.0,NaN,1.0,3,1,1622.280029,101,37,1,1,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,14.0,NaN,NaN,10,2,217,217,380.0,35,380,387,21,217,35,380,387.0,22,52,6,40.0,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1622.280029,1,12,36,3,5607,NaN,1.0,3,1,1622.280029,101,37,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,100,NaN,0.0,10,2,217,217,380,35,380,387,21,217,35,380,387,22,52,6,40,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,100,0,0,0,17,289,0,0,1,2080,1,28000.0,28000.0,0.0,28000.0,28000.0,13.461538,64.639999,101.653999,1.572618,21.169851,21.169851,3.052578,1,1,1,1,217,154.0,NaN,380,309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0,380.0,NaN,NaN,NaN,154.0,NaN,309.0,Commercial and service industry machinery manu...,NaN,NaN,NaN,NaN,NaN,3.052578,1,0,0,0,0,20,21,.,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
3,1990,67963,1,2689.909912,1,42,6,3.0,7400.0,NaN,1.0,3,1,2689.909912,101,34,1,1,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,18.0,NaN,NaN,10,2,64,64,732.0,99,740,808,21,64,99,740,808.0,22,47,4,50.0,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,2689.909912,1,42,6,3,7400,NaN,1.0,3,1,2689.909912,101,34,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,0.0,10,2,64,64,732,99,740,808,21,64,99,740,808,22,47,4,50,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,122,0,1,0,10,100,0,0,1,2115,1,27500.0,27500.0,5500.0,22000.0,27500.0,13.002364,64.639999,101.653999,1.572618,20.447746,20.447746,3.017873,1,1,1,1,64,102.0,NaN,740,738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,732.0,NaN,NaN,NaN,102.0,NaN,738.0,Computer systems design and related services,NaN,NaN,NaN,NaN,NaN,3.017873,0,0,0,1,0,74,20,Computer and Math Technicians,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1981,38650,9,1911.900024,1,31,51,3.0,8840.0,NaN,1.0,3,1,1911.900024,101,38,1,4,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,13.0,NaN,NaN,10,2,245,22,791.0,290,798,849,10,153,95,539,617.0,22,52,6,80.0,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,9,1911.900024,1,31,51,3,8840,NaN,1.0,3,1,1911.900024,101,38,1,700,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,90,NaN,NaN,10,2,245,22,791,290,798,849,10,153,95,539,617,22,52,6,80,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,700,0,0,0,1,90,0,0,0,19,361,0,0,1,2080,1,17000.0,17000.0,NaN,NaN,17000.0,8.173077,43.977001,101.653999,2.311526,18.892282,18.892282,2.938754,1,1,1,1,245,43.0,NaN,798,749,NaN,NaN,245.0,798.0,470.0,NaN,43.0,NaN,749.0,43.0,749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.938754,0,0,1,0,0,74,10,Managers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344282,1981,18574,2,970.179993,1,21,39,3.0,NaN,NaN,1.0,3,2,873.250000,1260,28,2,1,4,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,18.0,NaN,NaN,10,2,174,163,850.0,99,858,888,24,174,99,858,888.0,27,52,6,45.0,45,NaN,17000.0,0,0,NaN,NaN,NaN,5,NaN,NaN,0,0,NaN,0,NaN,2,970.179993,1,21,39,3,9997,NaN,1.0,3,2,873.250000,1260,28,2,100,4,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,NaN,10,2,174,163,850,99,858,888,24,174,99,858,888,27,52,6,45,45,NaN,17000.0,0,0,NaN,NaN,NaN,5,NaN,NaN,0,0,0,100,1,0,0,0,122,0,1,0,4,16,0,0,1,2340,1,17000.0,17000.0,NaN,NaN,17000.0,7.264957,43.977001,101.653999,2.311526,16.793140,16.793140,2.820971,0,1,1,1,174,200.0,NaN,858,787,NaN,NaN,174.0,858.0,200.0,NaN,200.0,NaN,787.0,200.0,787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.820971,0,1,0,0,1,72,23,Community and Social Workers,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
344283,1999,59820,7,1753.010010,1,42,6,3.0,7120.0,6053.0,NaN,3,4,1861.670044,301,27,2,1,1,1,9900.0,NaN,NaN,9900.0,9900.0,1.0,0.0,12.0,10.0,NaN,10,2,13,13,10.0,201,10,105,21,13,201,10,105.0,22,9,1,40.0,40,0.0,3200.0,0,0,3200.0,0.0,1.0,3,0.0,0.0,0,0,0.0,0,0.0,7,1753.010010,1,42,6,3,7120,6053.0,NaN,3,4,1861.670044,301,27,2,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,13,13,10,201,10,105,21,13,201,10,105,22,9,1,40,40,0.0,3200.0,0,0,3200.0,0.0,1.0,3,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,9,81,0,0,1,360,1,3200.0,3200.0,0.0,3200.0,3200.0,8.888889,79.933998,101.653999,1.271724,11.304215,11.304215,2.425176,0,1,1,0,13,5.0,NaN,10,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,17.0,Crop production,2.425176,0,0,0,1,1,10,10,Managers,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
344284,1981,58979,3,1971.020020,1,33,48,3.0,NaN,NaN,1.0,3,2,1971.020020,201,36,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,10,2,231,13,601.0,200,628,636,21,231,200,628,636.0,22,52,6,40.0,40,NaN,13000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,3,1971.020020,1,33,48,3,9997,NaN,1.0,3,2,1971.020020,201,36,2,100,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,50,NaN,NaN,10,2,231,13,601,200,628,636,21,231,200,628,636,22,52,6,40,40,NaN,13000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,100,1,0,0,0,50,0,0,0,18,324,0,0,1,2080,1,13000.0,13000.0,NaN,NaN,13000.0,6.250000,43.977001,101.653999,2.311526,14.447040,14.447040,2.670490,1,1,1,1,231,470.0,NaN,628,497,NaN,NaN,231.0,628.0,470.0,NaN,5.0,NaN,497.0,470.0,497.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.670490,0,0,1,0,1,50,40,.,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1
344285,2007,33540,2,715.510010,1,22,19,4.0,1960.0,19163.0,NaN,3,2,715.510010,201,49,2,4,1,1,50200.0,1981.0,2.0,50200.0,50200.0,5.0,0.0,18.0,18.0,NaN,10,2,2860,194,741.0,99,7490,899,21,2200,29,7870,888.0,22,25,2,6.0,10,0.0,8800.0,0,0,8000.0,800.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,2,715.510010,1,22,19,4,1960,19163.0,NaN,3,2,715.510010,201,49,2,651,1,1,50200.0,1981.0,2.0,50200.0,50200.0,5.0,0,125,18.0,0.0,10,2,2860,194,741,99,7490,899,21,2200,29,7870,888,22,25,2,6,10,0.0,8800.0,0,0,8000.0,800.0,1.0,1,0.0,0.0,0,0,0,651,0,0,0,1,125,0,1,0,25,625,0,0,1,250,0,8800.0,8800.0,800.0,8000.0,8800.0,35.200001,94.727997,101.653999,1.073115,37.773636,37.773636,3.631611,1,1,1,1,2860,286.0,NaN,7490,749,7490.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.631611,0,1,0,0,1,74,27,.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
344286,2013,81314,3,820.739990,1,41,49,NaN,NaN,NaN,NaN,3,2,820.739990,201,36,2,1,1,1,9900.0,NaN,NaN,9900.0,9900.0,1.0,0.0,13.0,11.0,3.0,10,2,4760,275,633.0,490,4790,659,21,4760,490,4790,659.0,22,52,6,22.0,24,0.0,15000.0,0,0,15000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,3,820.739990,1,41,49,0,9997,0.0,NaN,3,2,820.739990,201,36,2,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,81,11.0,3.0,10,2,4760,275,633,490,4790,659,21,4760,490,4790,659,22,52,6,22,24,0.0,15000.0,0,0,15000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,81,0,0,0,17,289,0,0,1,1248,0,15000.0,15000.0,0.0,15000.0,15000.0,12.019231,106.009003,101.653999,0.958919,11.525464,11.525464,2.444559,1,1,1,1,4760,476.0,4760.0,4790,479,NaN,4790.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.444559,0,0,0,1,1,50,40,.,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344287 entries, 0 to 344286
Columns: 234 entries, year to LEHS
dtypes: float64(85), int64(146), object(3)
memory usage: 614.6+ MB

In [6]:
print(df.columns.tolist())

['year', 'serial', 'numprec', 'hwtsupp', 'gq', 'region', 'statefip', 'metro', 'metarea', 'county', 'farm', 'month', 'pernum', 'wtsupp', 'relate', 'age', 'sex', 'race', 'marst', 'popstat', 'bpl', 'yrimmig', 'citizen', 'mbpl', 'fbpl', 'nativity', 'hispan', 'sch', 'educ99', 'schlcoll', 'empstat', 'labforce', 'occ', 'occ1990', 'ind1990', 'occ1950', 'ind', 'ind1950', 'classwkr', 'occly', 'occ50ly', 'indly', 'ind50ly', 'classwly', 'wkswork1', 'wkswork2', 'hrswork', 'uhrswork', 'union', 'incwage', 'incbus', 'incfarm', 'inclongj', 'oincwage', 'srcearn', 'ftype', 'quhrswor', 'qwkswork', 'qincbus', 'qincfarm', 'qinclong', 'qincwage', 'qsrcearn', 'o_numprec', 'o_hwtsupp', 'o_gq', 'o_region', 'o_statefip', 'o_metro', 'o_metarea', 'o_county', 'o_farm', 'o_month', 'o_pernum', 'o_wtsupp', 'o_relate', 'o_age', 'o_sex', 'o_race', 'o_marst', 'o_popstat', 'o_bpl', 'o_yrimmig', 'o_citizen', 'o_mbpl', 'o_fbpl', 'o_nativity', 'o_hispan', 'o_educ', 'o_educ99', 'o_schlcoll', 'o_empstat', 'o_labforce', 'o_occ', 'o_occ1990', 'o_ind1990', 'o_occ1950', 'o_ind', 'o_ind1950', 'o_classwkr', 'o_occly', 'o_occ50ly', 'o_indly', 'o_ind50ly', 'o_classwly', 'o_wkswork1', 'o_wkswork2', 'o_hrswork', 'o_uhrswork', 'o_union', 'o_incwage', 'o_incbus', 'o_incfarm', 'o_inclongj', 'o_oincwage', 'o_srcearn', 'o_ftype', 'o_quhrswor', 'o_qwkswork', 'o_qincbus', 'o_qincfarm', 'o_qincwage', 'origrace', 'white', 'black', 'hisp', 'othrace', 'educorig', 'ba', 'adv', 'groupquar', 'potexp', 'potexp2', 'selfemp', 'military', 'employed', 'annhrs', 'ft', 'niincwage', 'incwageman', 'tcoincwage', 'tcinclongj', 'tcincwage', 'hrwage', 'perconexp', 'expendbase10', 'inflate', 'realhrwage', 'uncenrealhrwage', 'lnrwg', 'hdwfcoh', 'notalloc', 'basesamp', 'wagesamp', 'occ_orig', 'adj_occ', 'occ_2010_orig', 'ind_orig', 'adj_ind', 'ind_2002_orig', 'ind_2007_orig', 'occ_81', 'ind_81', 'occ_2000female', 'unmatched_fem_81', 'occ_2000male', 'unmatched_male_81', 'ind_2000', 'occ2000_81', 'ind2000_81', 'occ_1990', 'ind_1990', 'occ_1999', 'ind_1999', 'unmatched_occ_90', 'occ2000_90', 'unmatched_ind_90', 'ind2000_90', 'indname2000_90', 'unmatched_occ_99', 'occ2000_99', 'unmatched_ind_99', 'ind2000_99', 'indname2000_99', 'un_lnrealwg', 'northeast', 'northcentral', 'south', 'west', 'female', 'adj_ind2', 'adj_occ2', 'adj_occ2name', 'Agriculture', 'miningconstruction', 'durables', 'nondurables', 'Transport', 'Utilities', 'Communications', 'retailtrade', 'wholesaletrade', 'finance', 'SocArtOther', 'hotelsrestaurants', 'Medical', 'Education', 'professional', 'publicadmin', 'sumadj_ind', 'manager', 'business', 'financialop', 'computer', 'architect', 'scientist', 'socialworker', 'postseceduc', 'legaleduc', 'artist', 'lawyerphysician', 'healthcare', 'healthsupport', 'protective', 'foodcare', 'building', 'sales', 'officeadmin', 'farmer', 'constructextractinstall', 'production', 'transport', 'sumadj_occ', 'LEHS']

In [7]:
coldrop = ['gq','metro','month','pernum','popstat','citizen','mbpl','fbpl','nativity','schlcoll','labforce']
df.drop(columns=coldrop,inplace=True)
df.head()

,year,serial,numprec,hwtsupp,region,statefip,metarea,county,farm,wtsupp,relate,age,sex,race,marst,bpl,yrimmig,hispan,sch,educ99,empstat,occ,occ1990,ind1990,occ1950,ind,ind1950,classwkr,occly,occ50ly,indly,ind50ly,classwly,wkswork1,wkswork2,hrswork,uhrswork,union,incwage,incbus,incfarm,inclongj,oincwage,srcearn,ftype,quhrswor,qwkswork,qincbus,qincfarm,qinclong,qincwage,qsrcearn,o_numprec,o_hwtsupp,o_gq,o_region,o_statefip,o_metro,o_metarea,o_county,o_farm,o_month,o_pernum,o_wtsupp,o_relate,o_age,o_sex,o_race,o_marst,o_popstat,o_bpl,o_yrimmig,o_citizen,o_mbpl,o_fbpl,o_nativity,o_hispan,o_educ,o_educ99,o_schlcoll,o_empstat,o_labforce,o_occ,o_occ1990,o_ind1990,o_occ1950,o_ind,o_ind1950,o_classwkr,o_occly,o_occ50ly,o_indly,o_ind50ly,o_classwly,o_wkswork1,o_wkswork2,o_hrswork,o_uhrswork,o_union,o_incwage,o_incbus,o_incfarm,o_inclongj,o_oincwage,o_srcearn,o_ftype,o_quhrswor,o_qwkswork,o_qincbus,o_qincfarm,o_qincwage,origrace,white,black,hisp,othrace,educorig,ba,adv,groupquar,potexp,potexp2,selfemp,military,employed,annhrs,ft,niincwage,incwageman,tcoincwage,tcinclongj,tcincwage,hrwage,perconexp,expendbase10,inflate,realhrwage,uncenrealhrwage,lnrwg,hdwfcoh,notalloc,basesamp,wagesamp,occ_orig,adj_occ,occ_2010_orig,ind_orig,adj_ind,ind_2002_orig,ind_2007_orig,occ_81,ind_81,occ_2000female,unmatched_fem_81,occ_2000male,unmatched_male_81,ind_2000,occ2000_81,ind2000_81,occ_1990,ind_1990,occ_1999,ind_1999,unmatched_occ_90,occ2000_90,unmatched_ind_90,ind2000_90,indname2000_90,unmatched_occ_99,occ2000_99,unmatched_ind_99,ind2000_99,indname2000_99,un_lnrealwg,northeast,northcentral,south,west,female,adj_ind2,adj_occ2,adj_occ2name,Agriculture,miningconstruction,durables,nondurables,Transport,Utilities,Communications,retailtrade,wholesaletrade,finance,SocArtOther,hotelsrestaurants,Medical,Education,professional,publicadmin,sumadj_ind,manager,business,financialop,computer,architect,scientist,socialworker,postseceduc,legaleduc,artist,lawyerphysician,healthcare,healthsupport,protective,foodcare,building,sales,officeadmin,farmer,constructextractinstall,production,transport,sumadj_occ,LEHS
0,1990,9677,1,1052.650024,12,36,5607.0,NaN,1.0,1052.650024,101,58,1,3,6,NaN,NaN,1.0,12.0,NaN,10,335,335,871.0,390,871,896,28,335,390,871,896.0,28,52,6,35.0,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1052.650024,1,12,36,2,5607,NaN,1.0,3,1,1052.650024,101,58,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,200,72,NaN,0.0,10,2,335,335,871,390,871,896,28,335,390,871,896,28,52,6,35,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0,100,0,0,1,0,72,0,0,0,40,1600,0,0,1,1820,1,14200.0,14200.0,0.0,14200.0,14200.0,7.802198,64.639999,101.653999,1.572618,12.269874,12.269874,2.507147,1,1,1,1,335,526.0,NaN,871,837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,871.0,NaN,NaN,NaN,526.0,NaN,837.0,Individual and family services,NaN,NaN,NaN,NaN,NaN,2.507147,1,0,0,0,0,62,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
1,2009,64923,4,971.200012,33,5,NaN,NaN,NaN,1288.880005,1260,28,1,1,6,9900.0,NaN,0.0,12.0,10.0,10,5120,337,762.0,310,8660,836,21,5120,310,8660,836.0,22,52,6,40.0,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0.0,0,0.0,4,971.200012,1,33,5,2,9999,0.0,NaN,3,4,1288.880005,1260,28,1,100,6,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,5120,337,762,310,8660,836,21,5120,310,8660,836,22,52,6,40,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,10,100,0,0,1,2080,1,17680.0,17680.0,0.0,17680.0,17680.0,8.500000,100.063004,101.653999,1.015900,8.635149,8.635149,2.155841,0,1,1,1,5120,512.0,NaN,8660,866,NaN,8660.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.155841,0,0,1,0,0,68,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
2,1990,8425,1,1622.280029,12,36,5607.0,NaN,1.0,1622.280029,101,37,1,1,6,NaN,NaN,0.0,14.0,NaN,10,217,217,380.0,35,380,387,21,217,35,380,387.0,22,52,6,40.0,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1622.280029,1,12,36,3,5607,NaN,1.0,3,1,1622.280029,101,37,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,100,NaN,0.0,10,2,217,217,380,35,380,387,21,217,35,380,387,22,52,6,40,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,100,0,0,0,17,289,0,0,1,2080,1,28000.0,28000.0,0.0,28000.0,28000.0,13.461538,64.639999,101.653999,1.572618,21.169851,21.169851,3.052578,1,1,1,1,217,154.0,NaN,380,309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0,380.0,NaN,NaN,NaN,154.0,NaN,309.0,Commercial and service industry machinery manu...,NaN,NaN,NaN,NaN,NaN,3.052578,1,0,0,0,0,20,21,.,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
3,1990,67963,1,2689.909912,42,6,7400.0,NaN,1.0,2689.909912,101,34,1,1,6,NaN,NaN,0.0,18.0,NaN,10,64,64,732.0,99,740,808,21,64,99,740,808.0,22,47,4,50.0,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,2689.909912,1,42,6,3,7400,NaN,1.0,3,1,2689.909912,101,34,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,0.0,10,2,64,64,732,99,740,808,21,64,99,740,808,22,47,4,50,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,122,0,1,0,10,100,0,0,1,2115,1,27500.0,27500.0,5500.0,22000.0,27500.0,13.002364,64.639999,101.653999,1.572618,20.447746,20.447746,3.017873,1,1,1,1,64,102.0,NaN,740,738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,732.0,NaN,NaN,NaN,102.0,NaN,738.0,Computer systems design and related services,NaN,NaN,NaN,NaN,NaN,3.017873,0,0,0,1,0,74,20,Computer and Math Technicians,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1981,38650,9,1911.900024,31,51,8840.0,NaN,1.0,1911.900024,101,38,1,4,1,NaN,NaN,0.0,13.0,NaN,10,245,22,791.0,290,798,849,10,153,95,539,617.0,22,52,6,80.0,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,9,1911.900024,1,31,51,3,8840,NaN,1.0,3,1,1911.900024,101,38,1,700,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,90,NaN,NaN,10,2,245,22,791,290,798,849,10,153,95,539,617,22,52,6,80,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,700,0,0,0,1,90,0,0,0,19,361,0,0,1,2080,1,17000.0,17000.0,NaN,NaN,17000.0,8.173077,43.977001,101.653999,2.311526,18.892282,18.892282,2.938754,1,1,1,1,245,43.0,NaN,798,749,NaN,NaN,245.0,798.0,470.0,NaN,43.0,NaN,749.0,43.0,749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.938754,0,0,1,0,0,74,10,Managers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1

redressing columns

In [8]:
def fix_relation_value(code):
    if code == 101:
        return 'head'
    elif code == 201:
        return 'spouse'
    elif code == 301:
        return 'child'
    elif code == 303:
        return 'stepchild'
    elif code == 501:
        return 'parent'
    elif code == 701:
        return 'sibling'
    elif code == 901:
        return 'grandchild'
    elif code == 1001:
        return 'other'
    elif code == 1113:
        return 'partner'
    elif code == 1115:
        return 'housemate'
    elif code == 1241:
        return 'roomer'
    elif code == 1242:
        return 'foster'
    elif code == 1260:
        return 'non-relate'

In [9]:
df['relate'].apply(fix_relation_value) #testing

0               head
1         non-relate
2               head
3               head
4               head
             ...
344282    non-relate
344283         child
344284        spouse
344285        spouse
344286        spouse
Name: relate, Length: 344287, dtype: object

In [10]:
df['relate']=df['relate'].apply(fix_relation_value)

In [12]:
df.head(20)

,year,serial,numprec,hwtsupp,region,statefip,metarea,county,farm,wtsupp,relate,age,sex,race,marst,bpl,yrimmig,hispan,sch,educ99,empstat,occ,occ1990,ind1990,occ1950,ind,ind1950,classwkr,occly,occ50ly,indly,ind50ly,classwly,wkswork1,wkswork2,hrswork,uhrswork,union,incwage,incbus,incfarm,inclongj,oincwage,srcearn,ftype,quhrswor,qwkswork,qincbus,qincfarm,qinclong,qincwage,qsrcearn,o_numprec,o_hwtsupp,o_gq,o_region,o_statefip,o_metro,o_metarea,o_county,o_farm,o_month,o_pernum,o_wtsupp,o_relate,o_age,o_sex,o_race,o_marst,o_popstat,o_bpl,o_yrimmig,o_citizen,o_mbpl,o_fbpl,o_nativity,o_hispan,o_educ,o_educ99,o_schlcoll,o_empstat,o_labforce,o_occ,o_occ1990,o_ind1990,o_occ1950,o_ind,o_ind1950,o_classwkr,o_occly,o_occ50ly,o_indly,o_ind50ly,o_classwly,o_wkswork1,o_wkswork2,o_hrswork,o_uhrswork,o_union,o_incwage,o_incbus,o_incfarm,o_inclongj,o_oincwage,o_srcearn,o_ftype,o_quhrswor,o_qwkswork,o_qincbus,o_qincfarm,o_qincwage,origrace,white,black,hisp,othrace,educorig,ba,adv,groupquar,potexp,potexp2,selfemp,military,employed,annhrs,ft,niincwage,incwageman,tcoincwage,tcinclongj,tcincwage,hrwage,perconexp,expendbase10,inflate,realhrwage,uncenrealhrwage,lnrwg,hdwfcoh,notalloc,basesamp,wagesamp,occ_orig,adj_occ,occ_2010_orig,ind_orig,adj_ind,ind_2002_orig,ind_2007_orig,occ_81,ind_81,occ_2000female,unmatched_fem_81,occ_2000male,unmatched_male_81,ind_2000,occ2000_81,ind2000_81,occ_1990,ind_1990,occ_1999,ind_1999,unmatched_occ_90,occ2000_90,unmatched_ind_90,ind2000_90,indname2000_90,unmatched_occ_99,occ2000_99,unmatched_ind_99,ind2000_99,indname2000_99,un_lnrealwg,northeast,northcentral,south,west,female,adj_ind2,adj_occ2,adj_occ2name,Agriculture,miningconstruction,durables,nondurables,Transport,Utilities,Communications,retailtrade,wholesaletrade,finance,SocArtOther,hotelsrestaurants,Medical,Education,professional,publicadmin,sumadj_ind,manager,business,financialop,computer,architect,scientist,socialworker,postseceduc,legaleduc,artist,lawyerphysician,healthcare,healthsupport,protective,foodcare,building,sales,officeadmin,farmer,constructextractinstall,production,transport,sumadj_occ,LEHS
0,1990,9677,1,1052.650024,12,36,5607.0,NaN,1.0,1052.650024,head,58,1,3,6,NaN,NaN,1.0,12.0,NaN,10,335,335,871.0,390,871,896,28,335,390,871,896.0,28,52,6,35.0,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1052.650024,1,12,36,2,5607,NaN,1.0,3,1,1052.650024,101,58,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,200,72,NaN,0.0,10,2,335,335,871,390,871,896,28,335,390,871,896,28,52,6,35,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0,100,0,0,1,0,72,0,0,0,40,1600,0,0,1,1820,1,14200.0,14200.0,0.0,14200.0,14200.0,7.802198,64.639999,101.653999,1.572618,12.269874,12.269874,2.507147,1,1,1,1,335,526.0,NaN,871,837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,871.0,NaN,NaN,NaN,526.0,NaN,837.0,Individual and family services,NaN,NaN,NaN,NaN,NaN,2.507147,1,0,0,0,0,62,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
1,2009,64923,4,971.200012,33,5,NaN,NaN,NaN,1288.880005,non-relate,28,1,1,6,9900.0,NaN,0.0,12.0,10.0,10,5120,337,762.0,310,8660,836,21,5120,310,8660,836.0,22,52,6,40.0,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0.0,0,0.0,4,971.200012,1,33,5,2,9999,0.0,NaN,3,4,1288.880005,1260,28,1,100,6,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,5120,337,762,310,8660,836,21,5120,310,8660,836,22,52,6,40,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,10,100,0,0,1,2080,1,17680.0,17680.0,0.0,17680.0,17680.0,8.500000,100.063004,101.653999,1.015900,8.635149,8.635149,2.155841,0,1,1,1,5120,512.0,NaN,8660,866,NaN,8660.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.155841,0,0,1,0,0,68,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
2,1990,8425,1,1622.280029,12,36,5607.0,NaN,1.0,1622.280029,head,37,1,1,6,NaN,NaN,0.0,14.0,NaN,10,217,217,380.0,35,380,387,21,217,35,380,387.0,22,52,6,40.0,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1622.280029,1,12,36,3,5607,NaN,1.0,3,1,1622.280029,101,37,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,100,NaN,0.0,10,2,217,217,380,35,380,387,21,217,35,380,387,22,52,6,40,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,100,0,0,0,17,289,0,0,1,2080,1,28000.0,28000.0,0.0,28000.0,28000.0,13.461538,64.639999,101.653999,1.572618,21.169851,21.169851,3.052578,1,1,1,1,217,154.0,NaN,380,309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0,380.0,NaN,NaN,NaN,154.0,NaN,309.0,Commercial and service industry machinery manu...,NaN,NaN,NaN,NaN,NaN,3.052578,1,0,0,0,0,20,21,.,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
3,1990,67963,1,2689.909912,42,6,7400.0,NaN,1.0,2689.909912,head,34,1,1,6,NaN,NaN,0.0,18.0,NaN,10,64,64,732.0,99,740,808,21,64,99,740,808.0,22,47,4,50.0,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,2689.909912,1,42,6,3,7400,NaN,1.0,3,1,2689.909912,101,34,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,0.0,10,2,64,64,732,99,740,808,21,64,99,740,808,22,47,4,50,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,122,0,1,0,10,100,0,0,1,2115,1,27500.0,27500.0,5500.0,22000.0,27500.0,13.002364,64.639999,101.653999,1.572618,20.447746,20.447746,3.017873,1,1,1,1,64,102.0,NaN,740,738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,732.0,NaN,NaN,NaN,102.0,NaN,738.0,Computer systems design and related services,NaN,NaN,NaN,NaN,NaN,3.017873,0,0,0,1,0,74,20,Computer and Math Technicians,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1981,38650,9,1911.900024,31,51,8840.0,NaN,1.0,1911.900024,head,38,1,4,1,NaN,NaN,0.0,13.0,NaN,10,245,22,791.0,290,798,849,10,153,95,539,617.0,22,52,6,80.0,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,9,1911.900024,1,31,51,3,8840,NaN,1.0,3,1,1911.900024,101,38,1,700,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,90,NaN,NaN,10,2,245,22,791,290,798,849,10,153,95,539,617,22,52,6,80,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,700,0,0,0,1,90,0,0,0,19,361,0,0,1,2080,1,17000.0,17000.0,NaN,NaN,17000.0,8.173077,43.977001,101.653999,2.311526,18.892282,18.892282,2.938754,1,1,1,1,245,43.0,NaN,798,749,NaN,NaN,245.0,798.0,470.0,NaN,43.0,NaN,749.0,43.0,749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.938754,0,0,1,0,0,74,10,Managers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
5,1999,63841,5,1858.479980,42,6,680.0,6029.0,NaN,1858.479980,head,37,1,3,1,9900.0,NaN,1.0,13.0,11.0,10,424,423,910.0,763,910,936,27,424,763,910,936.0,27,52,6,24.0,40,0.0,42000.0,0,0,42000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,5,1858.479980,1,42,6,2,680,6029.0,NaN,3,1,1858.479980,101,37,1,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,102,81,11.0,0.0,10,2,424,423,910,763,910,936,27,424,763,910,936,27,52,6,24,40,0.0,42000.0,0,0,42000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,0,0,1,0,81,0,0,0,18,324,0,0,1,2080,1,42000.0,42000.0,0.0,42000.0,42000.0,20.192308,79.933998,101.653999,1.271724,25.679049,25.679049,3.245675,1,1,1,1,424,380.0,NaN,910,947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,424.0,910.0,NaN,NaN,NaN,NaN,NaN,NaN,380.0,NaN,947.0,"Justice, public order, and safety activities",3.245675,0,0,0,1,0,80,32,Protective Service adj_occupations,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1
6,2007,25381,5,1488.300049,21,17,1605.0,NaN,NaN,1488.300049,head,44,1,1,1,20000.0,1997.0,0.0,16.0,15.0,10,7750,785,351.0,690,3570,376,21,7750,690,3570,376.0,22,52,6,80.0,80,0.0,33000.0,0,0,17000.0,16000.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,5,1488.300049,1,21,17,3,1605,0.0,NaN,3,1,1488.300049,101,44,1,100,1,1,20000.0,1997.0,3.0,20000.0,20000.0,5.0,0,111,15.0,0.0,10,2,7750,785,351,690,3570,376,21,7750,690,3570,376,22,52,6,80,80,0.0,33000.0,0,0,17000.0,16000.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,111,1,0,0,22,484,0,0,1,4160,1,33000.0,33000.0,16000.0,17000.0,33000.0,7.932693,94.727997,101.653999,1.073115,8.512689,8.512689,2.141558,1,1,1,1,7750,775.0,NaN,3570,357,3570.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.141558,0,1,0,0,0,20,60,Production,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
7,1990,56727,2,1889.739990,33,48,1920.0,NaN,1.0,1889.739990,head,32,1,3,1,NaN,NaN,1.0,12.0,NaN,10,243,243,751.0,290,751,816,21,243,290,751,816.0,22,52,6,48.0,48,0.0,28000.0,0,0,28000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,2,1889.739990,1,33,48,3,1920,NaN,1.0,3,1,1889.739990,101,32,1,100,1,1,NaN,NaN,NaN,NaN,NaN,NaN,102,72,NaN,0.0,10,2,243,243,751,290,751,816,21,243,290,751,816,22,52,6,48,48,0.0,28000.0,0,0,28000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,0,0,1,0,72,0,0,0,14,196,0,0,1,2496,1,28000.0,28000.0,0.0,28000.0,28000.0,11.217949,64.639999,101.653999,1.572618,17.641542,17.641542,2.870256,1,1,1,1,243,470.0,NaN,751,877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,243.0,751.0,NaN,NaN,NaN,470.0,NaN,877.0,Automotive repair and maintenance,NaN,NaN,NaN,NaN,NaN,2.870256,0,0,1,0,0,62,40,.,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1
8,1999,28603,4,609.080017,31,10,9160.0,10003.0,NaN,609.080017,head,41,1,2,1,9900.0,NaN,0.0,12.0,10.0,10,308,308,410.0,341,410,526,21,308,341,410,526.0,22,52,6,40.0,40,0.0,30000.0,0,0,30000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,4,609.080017,1,31,10,4,9160,10003.0,NaN,3,1,609.080017,101,41,1,200,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,308,308,410,341,410,526,21,308,341,410,526,22,52,6,40,40,0.0,30000.0,0,0,30000.0,0.0,1.0,1,0.0,0.0,0,0,0,200,0,1,0,0,73,0,0,0,23,529,0,0,1,2080,1,30000.0,30000.0,0.0,30000.0,30000.0,14.423077,79.933998,101.653999,1.271724,18.342176,18.342176,2.909203,1,1,1,1,308,580.0,NaN,410,617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,410.0,NaN,NaN,NaN,NaN,NaN,NaN,580.0,NaN,617.0,Truck transportation,2.909203,0,0,1,0,0,42,42,Office and Admin Support,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
9,2011,5146,2,170.889999,11,50,1311.0,NaN,NaN,170.889999,spouse,55,1,2,1,9900.0,NaN,0.0,12.0,10.0,12,9620,889,831.0,970,8190,869,21,9620,970,2290,469.0,22,52,6,NaN,40,0.0,67000.0,0,0,67000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,2,170.889999,1,11,50,4,1311,0.0,NaN,3,2,170.889999,201,55,1,801,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,12,2,9620,889,831,970,8190,869,21,9620,970,2290,469,22,52,6,0,40,0.0,67000.0,0,0,67000.0,0.0,1.0,1,0.0,0.0,0,0,0,801,0,1,0,0,73,0,0,0,37,1369,0,0,1,2080,1,67000.0,67000.0,0.0,67000.0,67000.0,32.211540,101.653999,101.653999,1.000000,32.211540,32.211540,3.472325,1,1,1,1,9620,962.0,9620.0,8190,819,NaN,8190.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.472325,1,0,0,0,0,70,62,Transportation and materials moving,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1
10,2007,8087,4,270.209991,11,44,6483.0,NaN,NaN,270.209991,head,51,1,1,1,9900.0,NaN,0.0,13.0,11.0,10,4700,243,642.0,290,5070,669,21,4700,290,5070,669.0,22,52,6,50.0,50,0.0,125000.0,0,0,125000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,4,270.209991,1,11,44,3,6483,0.0,NaN,3,1,270.209991,101,51,1,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,81,11.0,0.0,10,2,4700,243,642,290,5070,669,21,4700,290,5070,669,22,52,6,50,50,0.0,125000.0,0,0,125000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,81,0,0,0,32,1024,0,0,1,2600,1,125000.0,125000.0,0.0,125000.0,125000.0,48.076923,94.727997,101.653999,1.073115,51.592049,51.592049,3.943367,1,1,1,1,4700,470.0,NaN,5070,507,5070.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.943367,1,0,0,0,0,50,40,.,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1
11,2009,18402,3,1648.250000,12,42,6161.0,42091.0,NaN,1648.250000,head,43,1,1,3,9900.0,NaN,0.0,16.0,15.0,10,7330,518,552.0,554,4490,618,21,7330,554,4490,618.0,22,52,6,43.0,43,0.0,52100.0,0,0,52100.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,3,1648.250000,1,12,42,3,6161,42091.0,NaN,3,1,1648.250000,101,43,1,100,3,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,111,15.0,0.0,10,2,7330,518,552,554,4490,618,21,7330,554,4490,618,22,52,6,43,43,0.0,52100.0,0,0,52100.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,111,1,0,0,21,441,0,0,1,2236,1,52100.0,52100.0,0.0,52100.0,52100.0,23.300537,100.063004,101.653999,1.015900,23.671013,23.671013,3.164251,1,1,1,1,7330,733.0,NaN,4490,449,NaN,4490.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.164251,1,0,0,0,0,52,52,"Consruction, Extraction, Installation",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
12,2011,87364,2,1457.709961,42,6,4483.0,6037.0,NaN,1457.709961,None,32,1,2,6,9900.0,NaN,0.0,16.0,15.0,10,2000,163,850.0,99,7870,888,21,910,99,7870,888.0,22,52,6,42.0,40,1.0,35000.0,0,0,35000.0,0.0,1.0,5,0.0,0.0,0,0,0.0,0,0.0,2,1457.709961,1,42,6,2,4483,6037.0,NaN,3,2,1457.709961,1114,32,1,200,6,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,111,15.0,0.0,10,2,2000,163,850,99,7870,888,21,910,99,7870,888,22,52,6,42,40,1.0,35000.0,0,0,35000.0,0.0,1.0,5,0.0,0.0,0,0,0,200,0,1,0,0,111,1,0,0,10,100,0,0,1,2080,1,35000.0,35000.0,0.0,35000.0,35000.0,16.826923,101.653999,101.653999,1.000000,16.826923,16.826923,2.822980,1,1,1,1,2000,200.0,2000.0,7870,787,NaN,7870.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.822980,0,0,0,1,0,72,23,Community and Social Workers,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
13,1999,40268,4,3231.620117,32,47,5360.0,NaN,NaN,3231.620117,head,33,1,1,1,9900.0,NaN,0.0,12.0,10.0,10,717,717,351.0,690,351,376,21,777,690,160,456.0,22,52,6,40.0,48,0.0,47771.0,0,0,47771.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,4,3231.620117,1,32,47,3,5360,0.0,NaN,3,1,3231.620117,101,33,1,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,717,717,351,690,351,376,21,777,690,160,456,22,52,6,40,48,0.0,47771.0,0,0,47771.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,15,225,0,0,1,2496,1,47771.0,47771.0,0.0,47771.0,47771.0,19.139023,79.933998,101.653999,1.271724,24.339560,24.339560,3.192103,1,1,1,1,717,822.0,NaN,351,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,717.0,351.0,NaN,NaN,NaN,NaN,NaN,NaN,822.0,NaN,357.0,Motor vehicles and motor vehicle equipment man...,3.192103,0,0,1,0,0,20,60,Production,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1
14,1990,1200,7,806.609985,11,33,NaN,NaN,1.0,806.609985,head,48,1,1,1,NaN,NaN,0.0,12.0,NaN,10,877,877,601.0,970,601,636,21,877,970,192,469.0,22,52,6,40.0,40,0.0,29000.0,0,0,29000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,7,806.609985,1,11,33,4,9999,NaN,1.0,3,1,806.609985,101,48,1,100,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,72,NaN,0.0,10,2,877,877,601,970,601,636,21,877,970,192,469,22,52,6,40,40,0.0,29000.0,0,0,29000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,72,0,0,0,30,900,0,0,1,2080,1,29000.0,29000.0,0.0,29000.0,29000.0,13.942307,64.639999,101.653999,1.572618,21.925917,21.925917,3.087669,1,1,1,1,877,562.0,NaN,601,497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,877.0,601.0,NaN,NaN,NaN,562.0,NaN,497.0,Grocery stores,NaN,NaN,NaN,NaN,NaN,3.087669,1,0,0,0,0,50,42,Office and Admin Support,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
15,1990,46230,2,1913.119995,31,12,5000.0,NaN,1.0,2231.409912,child,29,1,1,6,NaN,NaN,0.0,12.0,NaN,10,357,357,921.0,340,921,916,28,357,340,921,916.0,28,52,6,40.0,40,1.0,19000.0,0,0,19000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,2,1913.119995,1,31,12,3,5000,NaN,1.0,3,2,2231.409912,301,29,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,72,NaN,0.0,10,2,357,357,921,340,921,916,28,357,340,921,916,28,52,6,40,40,1.0,19000.0,0,0,19000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,72,0,0,0,11,121,0,0,1,2080,1,19000.0,19000.0,0.0,19000.0,19000.0,9.134615,64.639999,101.653999,1.572618,14.365255,14.365255,2.664813,0,1,1,1,357,551.0,NaN,921,938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,357.0,921.0,NaN,NaN,NaN,551.0,NaN,938.0,Public finance activities,NaN,NaN,NaN,NaN,NaN,2.664813,0,0,1,0,0,80,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
16,1981,2899,3,331.450012,11,50,NaN,NaN,1.0,331.450012,head,58,1,1,1,NaN,NaN,0.0,7.0,NaN,10,470,534,172.0,554,339,459,21,470,554,339,459.0,22,52,6,48.0,48,NaN,19000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,3,331.450012,1,11,50,1,9998,NaN,1.0,3,1,331.450012,101,58,1,100,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,31,NaN,NaN,10,2,470,534,172,554,339,459,21,470,554,339,459,22,52,6,48,48,NaN,19000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,100,1,0,0,0,31,0,0,0,40,1600,0,0,1,2496,1,19000.0,19000.0,NaN,NaN,19000.0,7.612179,43.977001,101.653999,2.311526,17.595753,17.595753,2.867658,1,1,1,1,470,731.0,NaN,339,199,NaN,NaN,470.0,339.0,731.0,NaN,731.0,NaN,199.0,731.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.867658,1,0,0,0,0,30,52,"Consruction, Extraction, Installation",0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1
17,1999,12331,4,1945.199951,12,42,6160.0,42029.0,NaN,1945.199951,head,49,1,1,1,9900.0,NaN,0.0,16.0,15.0,10,13,13,391.0,201,391,399,21,13,201,391,399.0,22,52,6,65.0,60,0.0,113000.0,0,0,105000.0,8000.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,4,1945.199951,1,12,42,3,6160,42029.0,NaN,3,1,1945.199951,101,49,1,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,111,15.0,0.0,10,2,13,13,391,201,391,399,21,13,201,391,399,22,52,6,65,60,0.0,113000.0,0,0,105000.0,8000.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,111,1,0,0,27,729,0,0,1,3120,1,113000.0,113000.0,8000.0,105000.0,113000.0,36.217949,79.933998,101.653999,1.271724,46.059242,46.059242,3.829928,1,1,1,1,13,5.0,NaN,391,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,391.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,398.0,"Miscellaneous manufacturing, n.e.c.",3.829928,1,0,0,0,0,20,10,Managers,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
18,2009,16325,3,1479.329956,12,34,5606.0,NaN,NaN,1479.329956,head,56,1,1,1,9900.0,NaN,0.0,18.0,18.0,10,2200,154,850.0,29,7870,888,21,2200,29,7870,888.0,22,44,4,40.0,40,1.0,38000.0,0,0,38000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,3,1479.329956,1,12,34,3,5606,0.0,NaN,3,1,1479.329956,101,56,1,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,125,18.0,0.0,10,2,2200,154,850,29,7870,888,21,2200,29,7870,888,22,44,4,40,40,1.0,38000.0,0,0,38000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,125,0,1,0,32,1024,0,0,1,1760,1,38000.0,38000.0,0.0,38000.0,38000.0,21.590910,100.063004,101.653999,1.015900,21.934204,21.934204,3.088047,1,1,1,1,2200,220.0,NaN,7870,787,NaN,7870.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.088047,1,0,0,0,0,72,25,.,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
19,2007,79001,5,529.080017,41,35,NaN,NaN,NaN,529.080017,spouse,30,1,1,1,9900.0,NaN,0.0,13.0,11.0,10,6660,35,931.0,533,9570,916,28,6660,533,9570,916.0,28,52,6,45.0,40,0.0,46000.0,0,0,38000.0,8000.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,5,529.080017,1,41,35,1,9998,0.0,NaN,3,2,529.080017,201,30,1,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,81,11.0,0.0,10,2,6660,35,931,533,9570,916,28,6660,533,9570,916,28,52,6,45,40,0.0,46000.0,0,0,38000.0,8000.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,81,0,0,0,11,121,0,0,1,2080,1,46000.0,46000.0,8000.0,38000.0,46000.0,22.115385,94.727997,101.653999,1.073115,23.732344,23.732344,3.166839,1,1,1,1,6660,666.0,NaN,9570,957,9570.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.166839,0,0,0,1,0,80,52,"Consruction, Extraction, Installation",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1

In [13]:
def fix_maritalstat_value(code):
    if code == 1:
        return 'present spouse'
    elif code == 2:
        return 'absent spouse'
    elif code == 3:
        return 'seprated'
    elif code == 4:
        return 'divorced'
    elif code == 5:
        return 'widowed'
    elif code == 6:
        return 'never married'

In [14]:
df['marst']=df['marst'].apply(fix_maritalstat_value)

In [15]:
df

,year,serial,numprec,hwtsupp,region,statefip,metarea,county,farm,wtsupp,relate,age,sex,race,marst,bpl,yrimmig,hispan,sch,educ99,empstat,occ,occ1990,ind1990,occ1950,ind,ind1950,classwkr,occly,occ50ly,indly,ind50ly,classwly,wkswork1,wkswork2,hrswork,uhrswork,union,incwage,incbus,incfarm,inclongj,oincwage,srcearn,ftype,quhrswor,qwkswork,qincbus,qincfarm,qinclong,qincwage,qsrcearn,o_numprec,o_hwtsupp,o_gq,o_region,o_statefip,o_metro,o_metarea,o_county,o_farm,o_month,o_pernum,o_wtsupp,o_relate,o_age,o_sex,o_race,o_marst,o_popstat,o_bpl,o_yrimmig,o_citizen,o_mbpl,o_fbpl,o_nativity,o_hispan,o_educ,o_educ99,o_schlcoll,o_empstat,o_labforce,o_occ,o_occ1990,o_ind1990,o_occ1950,o_ind,o_ind1950,o_classwkr,o_occly,o_occ50ly,o_indly,o_ind50ly,o_classwly,o_wkswork1,o_wkswork2,o_hrswork,o_uhrswork,o_union,o_incwage,o_incbus,o_incfarm,o_inclongj,o_oincwage,o_srcearn,o_ftype,o_quhrswor,o_qwkswork,o_qincbus,o_qincfarm,o_qincwage,origrace,white,black,hisp,othrace,educorig,ba,adv,groupquar,potexp,potexp2,selfemp,military,employed,annhrs,ft,niincwage,incwageman,tcoincwage,tcinclongj,tcincwage,hrwage,perconexp,expendbase10,inflate,realhrwage,uncenrealhrwage,lnrwg,hdwfcoh,notalloc,basesamp,wagesamp,occ_orig,adj_occ,occ_2010_orig,ind_orig,adj_ind,ind_2002_orig,ind_2007_orig,occ_81,ind_81,occ_2000female,unmatched_fem_81,occ_2000male,unmatched_male_81,ind_2000,occ2000_81,ind2000_81,occ_1990,ind_1990,occ_1999,ind_1999,unmatched_occ_90,occ2000_90,unmatched_ind_90,ind2000_90,indname2000_90,unmatched_occ_99,occ2000_99,unmatched_ind_99,ind2000_99,indname2000_99,un_lnrealwg,northeast,northcentral,south,west,female,adj_ind2,adj_occ2,adj_occ2name,Agriculture,miningconstruction,durables,nondurables,Transport,Utilities,Communications,retailtrade,wholesaletrade,finance,SocArtOther,hotelsrestaurants,Medical,Education,professional,publicadmin,sumadj_ind,manager,business,financialop,computer,architect,scientist,socialworker,postseceduc,legaleduc,artist,lawyerphysician,healthcare,healthsupport,protective,foodcare,building,sales,officeadmin,farmer,constructextractinstall,production,transport,sumadj_occ,LEHS
0,1990,9677,1,1052.650024,12,36,5607.0,NaN,1.0,1052.650024,head,58,1,3,never married,NaN,NaN,1.0,12.0,NaN,10,335,335,871.0,390,871,896,28,335,390,871,896.0,28,52,6,35.0,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1052.650024,1,12,36,2,5607,NaN,1.0,3,1,1052.650024,101,58,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,200,72,NaN,0.0,10,2,335,335,871,390,871,896,28,335,390,871,896,28,52,6,35,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0,100,0,0,1,0,72,0,0,0,40,1600,0,0,1,1820,1,14200.0,14200.0,0.0,14200.0,14200.0,7.802198,64.639999,101.653999,1.572618,12.269874,12.269874,2.507147,1,1,1,1,335,526.0,NaN,871,837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,871.0,NaN,NaN,NaN,526.0,NaN,837.0,Individual and family services,NaN,NaN,NaN,NaN,NaN,2.507147,1,0,0,0,0,62,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
1,2009,64923,4,971.200012,33,5,NaN,NaN,NaN,1288.880005,non-relate,28,1,1,never married,9900.0,NaN,0.0,12.0,10.0,10,5120,337,762.0,310,8660,836,21,5120,310,8660,836.0,22,52,6,40.0,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0.0,0,0.0,4,971.200012,1,33,5,2,9999,0.0,NaN,3,4,1288.880005,1260,28,1,100,6,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,5120,337,762,310,8660,836,21,5120,310,8660,836,22,52,6,40,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,10,100,0,0,1,2080,1,17680.0,17680.0,0.0,17680.0,17680.0,8.500000,100.063004,101.653999,1.015900,8.635149,8.635149,2.155841,0,1,1,1,5120,512.0,NaN,8660,866,NaN,8660.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.155841,0,0,1,0,0,68,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
2,1990,8425,1,1622.280029,12,36,5607.0,NaN,1.0,1622.280029,head,37,1,1,never married,NaN,NaN,0.0,14.0,NaN,10,217,217,380.0,35,380,387,21,217,35,380,387.0,22,52,6,40.0,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1622.280029,1,12,36,3,5607,NaN,1.0,3,1,1622.280029,101,37,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,100,NaN,0.0,10,2,217,217,380,35,380,387,21,217,35,380,387,22,52,6,40,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,100,0,0,0,17,289,0,0,1,2080,1,28000.0,28000.0,0.0,28000.0,28000.0,13.461538,64.639999,101.653999,1.572618,21.169851,21.169851,3.052578,1,1,1,1,217,154.0,NaN,380,309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0,380.0,NaN,NaN,NaN,154.0,NaN,309.0,Commercial and service industry machinery manu...,NaN,NaN,NaN,NaN,NaN,3.052578,1,0,0,0,0,20,21,.,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
3,1990,67963,1,2689.909912,42,6,7400.0,NaN,1.0,2689.909912,head,34,1,1,never married,NaN,NaN,0.0,18.0,NaN,10,64,64,732.0,99,740,808,21,64,99,740,808.0,22,47,4,50.0,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,2689.909912,1,42,6,3,7400,NaN,1.0,3,1,2689.909912,101,34,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,0.0,10,2,64,64,732,99,740,808,21,64,99,740,808,22,47,4,50,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,122,0,1,0,10,100,0,0,1,2115,1,27500.0,27500.0,5500.0,22000.0,27500.0,13.002364,64.639999,101.653999,1.572618,20.447746,20.447746,3.017873,1,1,1,1,64,102.0,NaN,740,738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,732.0,NaN,NaN,NaN,102.0,NaN,738.0,Computer systems design and related services,NaN,NaN,NaN,NaN,NaN,3.017873,0,0,0,1,0,74,20,Computer and Math Technicians,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1981,38650,9,1911.900024,31,51,8840.0,NaN,1.0,1911.900024,head,38,1,4,present spouse,NaN,NaN,0.0,13.0,NaN,10,245,22,791.0,290,798,849,10,153,95,539,617.0,22,52,6,80.0,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,9,1911.900024,1,31,51,3,8840,NaN,1.0,3,1,1911.900024,101,38,1,700,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,90,NaN,NaN,10,2,245,22,791,290,798,849,10,153,95,539,617,22,52,6,80,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,700,0,0,0,1,90,0,0,0,19,361,0,0,1,2080,1,17000.0,17000.0,NaN,NaN,17000.0,8.173077,43.977001,101.653999,2.311526,18.892282,18.892282,2.938754,1,1,1,1,245,43.0,NaN,798,749,NaN,NaN,245.0,798.0,470.0,NaN,43.0,NaN,749.0,43.0,749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.938754,0,0,1,0,0,74,10,Managers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344282,1981,18574,2,970.179993,21,39,NaN,NaN,1.0,873.250000,non-relate,28,2,1,divorced,NaN,NaN,0.0,18.0,NaN,10,174,163,850.0,99,858,888,24,174,99,858,888.0,27,52,6,45.0,45,NaN,17000.0,0,0,NaN,NaN,NaN,5,NaN,NaN,0,0,NaN,0,NaN,2,970.179993,1,21,39,3,9997,NaN,1.0,3,2,873.250000,1260,28,2,100,4,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,NaN,10,2,174,163,850,99,858,888,24,174,99,858,888,27,52,6,45,45,NaN,17000.0,0,0,NaN,NaN,NaN,5,NaN,NaN,0,0,0,100,1,0,0,0,122,0,1,0,4,16,0,0,1,2340,1,17000.0,17000.0,NaN,NaN,17000.0,7.264957,43.977001,101.653999,2.311526,16.793140,16.793140,2.820971,0,1,1,1,174,200.0,NaN,858,787,NaN,NaN,174.0,858.0,200.0,NaN,200.0,NaN,787.0,200.0,787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.820971,0,1,0,0,1,72,23,Community and Social Workers,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
344283,1999,59820,7,1753.010010,42,6,7120.0,6053.0,NaN,1861.670044,child,27,2,1,present spouse,9900.0,NaN,0.0,12.0,10.0,10,13,13,10.0,201,10,105,21,13,201,10,105.0,22,9,1,40.0,40,0.0,3200.0,0,0,3200.0,0.0,1.0,3,0.0,0.0,0,0,0.0,0,0.0,7,1753.010010,1,42,6,3,7120,6053.0,NaN,3,4,1861.670044,301,27,2,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,13,13,10,201,10,105,21,13,201,10,105,22,9,1,40,40,0.0,3200.0,0,0,3200.0,0.0,1.0,3,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,9,81,0,0,1,360,1,3200.0,3200.0,0.0,3200.0,3200.0,8.888889,79.933998,101.653999,1.271724,11.304215,11.304215,2.425176,0,1,1,0,13,5.0,NaN,10,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,17.0,Crop production,2.425176,0,0,0,1,1,10,10,Managers,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
344284,1981,58979,3,1971.020020,33,48,NaN,NaN,1.0,1971.020020,spouse,36,2,1,present spouse,NaN,NaN,0.0,10.0,NaN,10,231,13,601.0,200,628,636,21,231,200,628,636.0,22,52,6,40.0,40,NaN,13000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,3,1971.020020,1,33,48,3,9997,NaN,1.0,3,2,1971.020020,201,36,2,100,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,50,NaN,NaN,10,2,231,13,601,200,628,636,21,231,200,628,636,22,52,6,40,40,NaN,13000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,100,1,0,0,0,50,0,0,0,18,324,0,0,1,2080,1,13000.0,13000.0,NaN,NaN,13000.0,6.250000,43.977001,101.653999,2.311526,14.447040,14.447040,2.670490,1,1,1,1,231,470.0,NaN,628,497,NaN,NaN,231.0,628.0,470.0,NaN,5.0,NaN,497.0,470.0,497.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.670490,0,0,1,0,1,50,40,.,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1
344285,2007,33540,2,715.510010,22,19,1960.0,19163.0,NaN,715.510010,spouse,49,2,4,present spouse,50200.0,1981.0,0.0,18.0,18.0,10,2860,194,741.0,99,7490,899,21,2200,29,7870,888.0,22,25,2,6.0,10,0.0,8800.0,0,0,8000.0,800.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,2,715.510010,1,22,19,4,1960,19163.0,NaN,3,2,715.510010,201,49,2,651,1,1,50200.0,1981.0,2.0,50200.0,50200.0,5.0,0,125,18.0,0.0,10,2,2860,194,741,99,7490,899,21,2200,29,7870,888,22,25,2,6,10,0.0,8800.0,0,0,8000.0,800.0,1.0,1,0.0,0.0,0,0,0,651,0,0,0,1,125,0,1,0,25,625,0,0,1,250,0,8800.0,8800.0,800.0,8000.0,8800.0,35.200001,94.727997,101.653999,1.073115,37.773636,37.773636,3.631611,1,1,1,1,2860,286.0,NaN,7490,749,7490.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.631611,0,1,0,0,1,74,27,.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
344286,2013,81314,3,820.739990,41,49,NaN,NaN,NaN,820.739990,spouse,36,2,1,present spouse,9900.0,NaN,0.0,13.0,11.0,10,4760,275,633.0,490,4790,659,21,4760,490,4790,659.0,22,52,6,22.0,24,0.0,15000.0,0,0,15000.0,0.0,1.0,1,0.0,0.0,0,0,0.0,0,0.0,3,820.739990,1,41,49,0,9997,0.0,NaN,3,2,820.739990,201,36,2,100,1,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,81,11.0,3.0,10,2,4760,275,633,490,4790,659,21,4760,490,4790,659,22,52,6,22,24,0.0,15000.0,0,0,15000.0,0.0,1.0,1,0.0,0.0,0,0,0,100,1,0,0,0,81,0,0,0,17,289,0,0,1,1248,0,15000.0,15000.0,0.0,15000.0,15000.0,12.019231,106.009003,101.653999,0.958919,11.525464,11.525464,2.444559,1,1,1,1,4760,476.0,4760.0,4790,479,NaN,4790.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.444559,0,0,0,1,1,50,40,.,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1

In [16]:
def fix_employment_value(code):
    if code == 10:
        return 'employed'
    elif code == 12:
        return 'unemployed'

In [17]:
df['empstat']=df['empstat'].apply(fix_employment_value)